version: '3.7'

services:
  frontend:
    image: cr.eventool.online/eventool-frontend:$IMAGE_TAG
    networks:
      - proxy
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 10s
      replicas: 1
      labels:
        - 'traefik.enable=true'

        # Frontend service configuration
        - 'traefik.http.routers.frontend.rule=Host(`eventool.online`) && !PathPrefix(`/api`)'
        - 'traefik.http.routers.frontend.entrypoints=websecure'
        - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
        - 'traefik.http.routers.frontend.service=frontend-service'
        - 'traefik.http.services.frontend-service.loadbalancer.server.port=3000'

        # API router and service for redirecting to backend
        - 'traefik.http.routers.api-router.rule=Host(`eventool.online`) && PathPrefix(`/api`)'
        - 'traefik.http.routers.api-router.entrypoints=websecure'
        - 'traefik.http.routers.api-router.tls.certresolver=myresolver'
        - 'traefik.http.routers.api-router.service=api-service'
        - 'traefik.http.services.api-service.loadbalancer.server.port=443'
        - 'traefik.http.services.api-service.loadbalancer.server.scheme=https'
        - 'traefik.http.services.api-service.loadbalancer.passhostheader=true'
        - 'traefik.http.services.api-service.loadbalancer.server.url=https://backend.eventool.online'

networks:
  proxy:
    external: true