name: CI Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Get the version number from commit count
        id: versioning
        run: echo "VERSION=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: cr.eventool.online
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cr.eventool.online/eventool-frontend:${{ env.VERSION }}
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
  
  update-swarm:
    needs: build-and-push  # Ensure this job runs after the build-and-push job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace image tag in stack file
        run: |
          export IMAGE_TAG=${{ env.VERSION }}
          envsubst < path/to/your/stack-file.template.yml > path/to/your/stack-file.yml

      - name: Update Docker Swarm Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }}
          username: ${{ secrets.SWARM_MANAGER_USERNAME }}
          key: ${{ secrets.SWARM_MANAGER_SSH_KEY }}
          script: |
            docker stack deploy --with-registry-auth -c docker/eventool-frontend.yml eventool-frontend
